[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "dihiggs"
dynamic = ["version"]
description = "Modeling the di-Higgs differential cross section."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Harrison B. Prosper", email = "hprosper@fsu.edu" }]
dependencies = [
    "drwho @ git+https://github.com/hbprosper/drwho.git@main",
    "numpy",
    "pandas",
    "matplotlib",
    "torch",
]

[project.urls]
Homepage = "https://github.com/hbprosper/dihiggs"

[tool.setuptools]
packages = ["dihiggs"]

[tool.setuptools.dynamic]
version = {attr = "dihiggs.__version__"}
